
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ruc.db.analyzer.online.adapter.tidb.parser;

/** CUP generated interface containing symbol constants. */
public interface TidbSelectSymbol {
  /* terminals */
  public static final int AND = 10;
  public static final int LT = 12;
  public static final int NE = 16;
  public static final int PLUS = 2;
  public static final int OR = 11;
  public static final int RPAREN = 7;
  public static final int IN = 19;
  public static final int DATE = 22;
  public static final int NOT = 9;
  public static final int LPAREN = 6;
  public static final int GT = 13;
  public static final int LE = 14;
  public static final int STRING = 21;
  public static final int FLOAT = 24;
  public static final int EOF = 0;
  public static final int DIV = 4;
  public static final int CANONICAL_COLUMN_NAME = 23;
  public static final int GE = 15;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int LIKE = 18;
  public static final int EQ = 17;
  public static final int INTEGER = 20;
  public static final int ISNULL = 8;
  public static final int MUL = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "DIV",
  "MUL",
  "LPAREN",
  "RPAREN",
  "ISNULL",
  "NOT",
  "AND",
  "OR",
  "LT",
  "GT",
  "LE",
  "GE",
  "NE",
  "EQ",
  "LIKE",
  "IN",
  "INTEGER",
  "STRING",
  "DATE",
  "CANONICAL_COLUMN_NAME",
  "FLOAT"
  };
}

