// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/resources/pg/pg_select_lexer.jflex

package ruc.db.analyzer.online.adapter.pg.parser;

import ruc.db.utils.exception.analyze.IllegalCharacterException;
import ruc.db.analyzer.online.adapter.Token;
import java_cup.runtime.*;
import ruc.db.generator.constraintchain.filter.arithmetic.ArithmeticNodeType;
import ruc.db.generator.constraintchain.filter.operation.CompareOperator;

@SuppressWarnings("fallthrough")
public class PgSelectOperatorInfoLexer implements PgSelectSymbol, java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING_LITERAL = 2;
  public static final int STRING_LITERAL_DOUBLE_QUOTATION = 4;
  public static final int IN_LIST = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\2\1\1\2\2\3\1\2\22\0\1\4\1\5"+
    "\1\6\1\0\1\7\2\0\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\11\22\1\23"+
    "\1\0\1\24\1\25\1\26\2\0\1\27\1\30\1\31"+
    "\1\32\1\31\1\33\1\34\1\31\1\35\2\31\1\36"+
    "\1\37\1\40\1\41\2\31\1\42\1\43\1\44\1\45"+
    "\3\31\1\46\1\31\1\47\1\50\1\51\1\0\1\31"+
    "\1\0\1\52\1\53\1\54\1\55\1\56\1\31\1\57"+
    "\1\60\1\61\2\31\1\62\1\63\1\64\1\65\1\66"+
    "\1\31\1\67\1\70\1\71\1\72\1\73\1\74\1\75"+
    "\1\31\1\76\1\77\1\0\1\100\1\101\1\0\5\102"+
    "\1\103\u01a2\102\2\103\326\102\u0100\103";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\2\1\1\2\1\3\1\4\1\5"+
    "\1\6\1\7\1\1\1\10\1\11\1\12\2\13\1\1"+
    "\1\14\1\15\1\16\15\1\1\17\1\20\1\21\1\17"+
    "\1\22\1\23\1\24\1\25\1\24\1\1\1\26\4\0"+
    "\1\27\1\30\1\2\1\13\1\11\1\0\1\13\1\0"+
    "\1\31\1\26\1\0\1\32\5\0\1\33\7\0\1\34"+
    "\1\35\1\36\1\37\1\40\1\24\1\41\1\42\2\0"+
    "\1\11\1\0\1\13\7\0\1\43\1\2\2\0\1\44"+
    "\1\0\1\45\1\46\1\47\1\50\1\24\3\0\1\13"+
    "\14\0\1\24\1\0\1\51\1\0\1\13\11\0\1\52"+
    "\3\0\1\24\4\0\1\2\4\0\1\53\3\0\1\24"+
    "\11\0\1\54\1\0\1\24\7\0\1\24\5\0\1\55"+
    "\1\24\1\0\1\56\3\0\1\24\1\55\3\0\1\57"+
    "\24\0\1\56\15\0\1\56\3\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[233];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\104\0\210\0\314\0\u0110\0\u0154\0\u0198\0\u01dc"+
    "\0\u0220\0\u0264\0\u0110\0\u0110\0\u0110\0\u0110\0\u02a8\0\u02ec"+
    "\0\u0330\0\u0110\0\u0374\0\u03b8\0\u03fc\0\u0440\0\u0484\0\u04c8"+
    "\0\u050c\0\u0550\0\u0594\0\u05d8\0\u061c\0\u0660\0\u06a4\0\u06e8"+
    "\0\u072c\0\u0770\0\u07b4\0\u07f8\0\u083c\0\u0880\0\u0110\0\u08c4"+
    "\0\u0908\0\u0110\0\u0110\0\u094c\0\u0110\0\u0990\0\u09d4\0\u0110"+
    "\0\u0a18\0\u0a5c\0\u0550\0\u0aa0\0\u0550\0\u0110\0\u0110\0\u0ae4"+
    "\0\u0b28\0\u0b6c\0\u0bb0\0\u0bf4\0\u0110\0\u0c38\0\u0c7c\0\u0110"+
    "\0\u0cc0\0\u0d04\0\u0d48\0\u0d8c\0\u0dd0\0\u0550\0\u0e14\0\u0e58"+
    "\0\u0e9c\0\u0ee0\0\u0f24\0\u0f68\0\u0fac\0\u0110\0\u0110\0\u0110"+
    "\0\u0110\0\u0110\0\u0ff0\0\u0110\0\u0110\0\u1034\0\u1078\0\u10bc"+
    "\0\u1100\0\u1144\0\u1188\0\u11cc\0\u1210\0\u1254\0\u1298\0\u12dc"+
    "\0\u1320\0\u0550\0\u0550\0\u1364\0\u13a8\0\u0550\0\u13ec\0\u0550"+
    "\0\u0550\0\u0550\0\u0550\0\u1430\0\u1474\0\u14b8\0\u14fc\0\u1540"+
    "\0\u1584\0\u15c8\0\u160c\0\u1650\0\u1694\0\u16d8\0\u171c\0\u1760"+
    "\0\u17a4\0\u17e8\0\u182c\0\u1870\0\u18b4\0\u18f8\0\u14b8\0\u193c"+
    "\0\u1980\0\u19c4\0\u1a08\0\u1a4c\0\u1a90\0\u1ad4\0\u1b18\0\u1b5c"+
    "\0\u1ba0\0\u1be4\0\u0110\0\u1c28\0\u1c6c\0\u1cb0\0\u1cf4\0\u1d38"+
    "\0\u1d7c\0\u1dc0\0\u1e04\0\u1e48\0\u1e8c\0\u1ed0\0\u1f14\0\u1f58"+
    "\0\u0110\0\u1f9c\0\u1fe0\0\u2024\0\u2068\0\u20ac\0\u20f0\0\u2134"+
    "\0\u2178\0\u21bc\0\u2200\0\u2244\0\u2288\0\u22cc\0\u0110\0\u2310"+
    "\0\u2354\0\u2398\0\u23dc\0\u2420\0\u2464\0\u24a8\0\u24ec\0\u2530"+
    "\0\u2574\0\u25b8\0\u25fc\0\u2640\0\u2684\0\u26c8\0\u0550\0\u270c"+
    "\0\u2750\0\u2794\0\u27d8\0\u281c\0\u2860\0\u28a4\0\u0110\0\u28e8"+
    "\0\u292c\0\u2970\0\u0110\0\u29b4\0\u29f8\0\u2a3c\0\u2a80\0\u2ac4"+
    "\0\u2b08\0\u2b4c\0\u2b90\0\u2bd4\0\u2c18\0\u2c5c\0\u2ca0\0\u2ce4"+
    "\0\u2d28\0\u2d6c\0\u2db0\0\u2df4\0\u2e38\0\u2e7c\0\u2ec0\0\u2f04"+
    "\0\u2f48\0\u2f8c\0\u2fd0\0\u3014\0\u3058\0\u309c\0\u30e0\0\u3124"+
    "\0\u3168\0\u31ac\0\u31f0\0\u3234\0\u3278\0\u0110\0\u32bc\0\u3300"+
    "\0\u3344";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[233];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\0\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\3\32"+
    "\1\33\1\32\1\34\2\32\1\35\1\36\1\32\1\37"+
    "\3\32\3\5\1\40\10\32\1\41\1\42\1\43\2\32"+
    "\1\44\6\32\2\5\1\45\1\5\1\0\2\46\1\0"+
    "\5\46\1\47\37\46\1\50\33\46\2\51\1\0\3\51"+
    "\1\52\41\51\1\50\33\51\1\5\2\6\1\0\1\6"+
    "\1\5\1\53\1\54\5\5\1\55\3\54\2\56\4\5"+
    "\20\54\3\5\25\54\1\5\1\57\1\5\2\54\105\0"+
    "\2\6\1\0\1\6\124\0\1\60\53\0\1\61\72\0"+
    "\1\62\22\0\1\63\7\0\1\64\1\0\2\65\4\0"+
    "\20\63\3\0\25\63\104\0\1\66\10\0\1\67\121\0"+
    "\1\70\102\0\2\21\70\0\1\63\7\0\1\71\1\0"+
    "\2\72\4\0\20\63\3\0\25\63\14\0\1\63\7\0"+
    "\1\71\1\0\2\73\4\0\20\63\3\0\25\63\30\0"+
    "\1\74\105\0\1\75\1\76\61\0\1\77\124\0\1\100"+
    "\65\0\1\63\7\0\1\64\1\0\2\63\4\0\11\63"+
    "\1\101\6\63\3\0\25\63\14\0\1\63\7\0\1\64"+
    "\1\0\2\63\4\0\20\63\3\0\25\63\14\0\1\63"+
    "\7\0\1\64\1\0\2\63\4\0\12\63\1\102\1\103"+
    "\4\63\3\0\25\63\14\0\1\63\7\0\1\64\1\0"+
    "\2\63\4\0\14\63\1\104\3\63\3\0\25\63\14\0"+
    "\1\63\7\0\1\64\1\0\2\63\4\0\12\63\1\105"+
    "\5\63\3\0\25\63\14\0\1\63\7\0\1\64\1\0"+
    "\2\63\4\0\13\63\1\106\4\63\3\0\25\63\14\0"+
    "\1\63\7\0\1\64\1\0\2\63\4\0\16\63\1\107"+
    "\1\63\3\0\25\63\14\0\1\63\7\0\1\64\1\0"+
    "\2\63\4\0\20\63\3\0\12\63\1\110\6\63\1\111"+
    "\3\63\14\0\1\63\7\0\1\64\1\0\2\63\4\0"+
    "\20\63\3\0\1\112\6\63\1\113\15\63\14\0\1\63"+
    "\7\0\1\64\1\0\2\63\4\0\20\63\3\0\13\63"+
    "\1\114\11\63\14\0\1\63\7\0\1\64\1\0\2\63"+
    "\4\0\20\63\3\0\15\63\1\106\7\63\14\0\1\63"+
    "\7\0\1\64\1\0\2\63\4\0\20\63\3\0\20\63"+
    "\1\115\4\63\106\0\1\116\2\0\2\46\1\0\5\46"+
    "\1\0\37\46\1\0\33\46\6\0\1\117\55\0\1\120"+
    "\2\0\1\121\1\0\1\122\12\0\2\51\1\0\3\51"+
    "\1\0\41\51\1\0\33\51\7\0\1\54\6\0\5\54"+
    "\4\0\20\54\3\0\25\54\3\0\2\54\7\0\1\54"+
    "\6\0\3\54\2\123\4\0\20\54\3\0\25\54\3\0"+
    "\2\54\10\0\1\124\174\0\1\125\74\0\1\126\20\0"+
    "\1\127\11\0\2\127\4\0\20\127\3\0\25\127\26\0"+
    "\2\70\70\0\1\127\11\0\2\130\4\0\20\127\3\0"+
    "\25\127\14\0\1\63\7\0\1\64\1\0\2\131\4\0"+
    "\20\63\3\0\25\63\14\0\1\63\7\0\1\71\1\0"+
    "\2\132\4\0\20\63\3\0\25\63\60\0\1\133\1\0"+
    "\1\134\3\0\1\135\2\0\1\136\4\0\1\137\16\0"+
    "\1\140\126\0\1\141\63\0\1\63\7\0\1\64\1\0"+
    "\2\63\4\0\3\63\1\142\14\63\3\0\25\63\14\0"+
    "\1\63\7\0\1\64\1\0\2\63\4\0\13\63\1\143"+
    "\4\63\3\0\25\63\14\0\1\63\7\0\1\64\1\0"+
    "\2\63\4\0\12\63\1\144\5\63\3\0\25\63\11\0"+
    "\1\145\2\0\1\63\7\0\1\64\1\0\2\63\4\0"+
    "\20\63\3\0\25\63\14\0\1\63\7\0\1\64\1\0"+
    "\2\63\4\0\15\63\1\146\2\63\3\0\25\63\14\0"+
    "\1\63\7\0\1\64\1\0\2\63\4\0\1\63\1\147"+
    "\16\63\3\0\25\63\14\0\1\63\7\0\1\64\1\0"+
    "\2\63\4\0\20\63\3\0\3\63\1\142\21\63\14\0"+
    "\1\63\7\0\1\64\1\0\2\63\4\0\20\63\3\0"+
    "\5\63\1\150\17\63\14\0\1\63\7\0\1\64\1\0"+
    "\2\63\4\0\20\63\3\0\23\63\1\151\1\63\14\0"+
    "\1\63\7\0\1\64\1\0\2\63\4\0\20\63\3\0"+
    "\12\63\1\152\12\63\14\0\1\63\7\0\1\64\1\0"+
    "\2\63\4\0\20\63\3\0\17\63\1\146\5\63\14\0"+
    "\1\63\7\0\1\64\1\0\2\63\4\0\20\63\3\0"+
    "\11\63\1\153\13\63\14\0\1\54\6\0\3\54\2\154"+
    "\4\0\20\54\3\0\25\54\3\0\2\54\53\0\1\155"+
    "\37\0\1\127\7\0\1\156\1\0\2\127\4\0\20\127"+
    "\3\0\25\127\14\0\1\127\7\0\1\156\1\0\2\130"+
    "\4\0\20\127\3\0\25\127\14\0\1\63\7\0\1\64"+
    "\1\0\2\157\4\0\20\63\3\0\25\63\14\0\1\63"+
    "\7\0\1\71\1\0\2\160\4\0\20\63\3\0\25\63"+
    "\66\0\1\161\4\0\1\162\67\0\1\163\12\0\1\164"+
    "\102\0\1\165\111\0\1\166\67\0\1\167\2\0\1\170"+
    "\51\0\1\171\114\0\1\172\52\0\1\63\7\0\1\64"+
    "\1\0\2\63\4\0\10\63\1\143\7\63\3\0\25\63"+
    "\45\0\1\173\52\0\1\63\7\0\1\64\1\0\2\63"+
    "\4\0\14\63\1\174\3\63\3\0\25\63\14\0\1\54"+
    "\6\0\3\54\2\175\4\0\20\54\3\0\25\54\3\0"+
    "\2\54\70\0\1\176\22\0\1\177\11\0\2\177\4\0"+
    "\20\177\3\0\25\177\14\0\1\63\6\0\1\200\1\64"+
    "\1\0\2\63\4\0\20\63\3\0\25\63\14\0\1\63"+
    "\6\0\1\200\1\71\1\0\2\201\4\0\20\63\3\0"+
    "\25\63\64\0\1\202\100\0\1\203\120\0\1\204\104\0"+
    "\1\205\102\0\1\206\75\0\1\207\115\0\1\210\71\0"+
    "\1\211\56\0\1\212\113\0\1\213\76\0\1\214\3\0"+
    "\1\215\45\0\1\63\7\0\1\64\1\0\2\63\4\0"+
    "\15\63\1\216\2\63\3\0\25\63\14\0\1\54\6\0"+
    "\1\217\4\54\4\0\20\54\3\0\25\54\3\0\2\54"+
    "\71\0\1\220\33\0\2\221\70\0\1\63\7\0\1\71"+
    "\1\0\2\201\4\0\20\63\3\0\25\63\66\0\1\222"+
    "\102\0\1\223\101\0\1\224\100\0\1\225\106\0\1\226"+
    "\103\0\1\227\116\0\1\224\70\0\1\230\63\0\1\231"+
    "\111\0\1\232\75\0\1\233\54\0\1\63\7\0\1\64"+
    "\1\0\2\63\4\0\13\63\1\234\4\63\3\0\25\63"+
    "\14\0\1\54\6\0\3\54\2\235\4\0\20\54\3\0"+
    "\25\54\3\0\2\54\67\0\1\236\35\0\2\237\145\0"+
    "\1\210\71\0\1\240\100\0\1\241\116\0\1\242\100\0"+
    "\1\243\113\0\1\244\104\0\1\245\17\0\1\246\135\0"+
    "\1\247\54\0\1\63\7\0\1\64\1\0\2\63\4\0"+
    "\6\63\1\250\11\63\3\0\25\63\14\0\1\54\6\0"+
    "\3\54\2\251\4\0\20\54\3\0\25\54\3\0\2\54"+
    "\61\0\1\252\40\0\1\253\154\0\1\224\65\0\1\67"+
    "\110\0\1\254\103\0\1\240\106\0\1\255\113\0\1\256"+
    "\52\0\1\257\52\0\1\63\7\0\1\64\1\0\2\63"+
    "\4\0\11\63\1\260\6\63\3\0\25\63\14\0\1\54"+
    "\6\0\1\261\4\54\4\0\20\54\3\0\25\54\3\0"+
    "\2\54\64\0\1\262\40\0\2\263\65\0\1\264\153\0"+
    "\1\67\101\0\1\265\76\0\1\266\45\0\1\63\7\0"+
    "\1\64\1\0\2\63\4\0\5\63\1\267\12\63\3\0"+
    "\25\63\14\0\1\54\6\0\3\54\2\270\4\0\20\54"+
    "\3\0\25\54\3\0\2\54\57\0\1\271\45\0\2\272"+
    "\147\0\1\273\100\0\1\274\56\0\1\275\54\0\1\54"+
    "\6\0\3\54\2\276\4\0\20\54\3\0\25\54\3\0"+
    "\2\54\6\0\1\277\101\0\1\300\166\0\1\301\102\0"+
    "\1\302\53\0\1\303\51\0\1\300\2\0\1\54\6\0"+
    "\5\54\4\0\20\54\3\0\25\54\3\0\2\54\21\0"+
    "\2\304\137\0\1\305\31\0\1\306\120\0\2\307\135\0"+
    "\1\310\123\0\1\311\32\0\1\312\141\0\1\313\103\0"+
    "\1\314\43\0\2\315\151\0\1\316\104\0\1\317\33\0"+
    "\2\320\142\0\1\321\102\0\1\322\46\0\1\323\145\0"+
    "\1\324\103\0\1\325\37\0\2\326\145\0\1\67\111\0"+
    "\1\327\32\0\2\330\152\0\1\331\31\0\1\332\70\0"+
    "\1\333\120\0\2\334\152\0\1\335\33\0\2\336\142\0"+
    "\1\337\43\0\2\340\144\0\1\341\41\0\2\342\137\0"+
    "\1\343\46\0\2\344\65\0\1\345\120\0\2\346\157\0"+
    "\1\347\72\0\1\350\102\0\1\351\75\0\1\67\25\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[13192];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\5\1\4\11\3\1\1\11\24\1\1\11"+
    "\2\1\2\11\1\1\1\11\2\1\1\11\4\0\1\1"+
    "\2\11\2\1\1\0\1\1\1\0\1\11\1\1\1\0"+
    "\1\11\5\0\1\1\7\0\5\11\1\1\2\11\2\0"+
    "\1\1\1\0\1\1\7\0\2\1\2\0\1\1\1\0"+
    "\5\1\3\0\1\1\14\0\1\1\1\0\1\1\1\0"+
    "\1\1\11\0\1\11\3\0\1\1\4\0\1\1\4\0"+
    "\1\11\3\0\1\1\11\0\1\11\1\0\1\1\7\0"+
    "\1\1\5\0\2\1\1\0\1\1\3\0\1\1\1\11"+
    "\3\0\1\11\24\0\1\1\15\0\1\11\3\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[233];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  private StringBuilder str_buff = new StringBuilder();
  private Symbol symbol(int type) {
    return new Token(PgSelectSymbol.terminalNames, type, yycolumn+1);
  }

  private Symbol symbol(int type, Object value) {
    return new Token(PgSelectSymbol.terminalNames, type, yycolumn+1, value);
  }

  public void init() {
    System.out.println("initialized");
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PgSelectOperatorInfoLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
    , ruc.db.utils.exception.TouchstoneException

  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new IllegalCharacterException(yytext(), yyline + 1, yycolumn + 1);
            }
          // fall through
          case 48: break;
          case 2:
            { 
            }
          // fall through
          case 49: break;
          case 3:
            { str_buff.setLength(0); yybegin(STRING_LITERAL);
            }
          // fall through
          case 50: break;
          case 4:
            { return symbol(LPAREN);
            }
          // fall through
          case 51: break;
          case 5:
            { return symbol(RPAREN);
            }
          // fall through
          case 52: break;
          case 6:
            { return symbol(MUL, ArithmeticNodeType.MUL);
            }
          // fall through
          case 53: break;
          case 7:
            { return symbol(PLUS, ArithmeticNodeType.PLUS);
            }
          // fall through
          case 54: break;
          case 8:
            { return symbol(MINUS, ArithmeticNodeType.MINUS);
            }
          // fall through
          case 55: break;
          case 9:
            { return symbol(FLOAT, Float.valueOf(yytext()));
            }
          // fall through
          case 56: break;
          case 10:
            { return symbol(DIV, ArithmeticNodeType.DIV);
            }
          // fall through
          case 57: break;
          case 11:
            { return symbol(INTEGER, yytext());
            }
          // fall through
          case 58: break;
          case 12:
            { return symbol(LT, CompareOperator.LT);
            }
          // fall through
          case 59: break;
          case 13:
            { return symbol(EQ, CompareOperator.EQ);
            }
          // fall through
          case 60: break;
          case 14:
            { return symbol(GT, CompareOperator.GT);
            }
          // fall through
          case 61: break;
          case 15:
            { str_buff.append( yytext() );
            }
          // fall through
          case 62: break;
          case 16:
            { yybegin(YYINITIAL);
    return symbol(STRING, str_buff.toString());
            }
          // fall through
          case 63: break;
          case 17:
            { str_buff.append('\\');
            }
          // fall through
          case 64: break;
          case 18:
            { yybegin(IN_LIST);
    return symbol(STRING, str_buff.toString());
            }
          // fall through
          case 65: break;
          case 19:
            { str_buff.setLength(0); yybegin(STRING_LITERAL_DOUBLE_QUOTATION);
            }
          // fall through
          case 66: break;
          case 20:
            { str_buff.append( yytext() );
    return symbol(STRING, str_buff.toString());
            }
          // fall through
          case 67: break;
          case 21:
            { str_buff.setLength(0);
            }
          // fall through
          case 68: break;
          case 22:
            { return symbol(NE, CompareOperator.NE);
            }
          // fall through
          case 69: break;
          case 23:
            { return symbol(VIRTUALNUM, yytext());
            }
          // fall through
          case 70: break;
          case 24:
            { str_buff.setLength(0);
    yybegin(IN_LIST);
            }
          // fall through
          case 71: break;
          case 25:
            { return symbol(LE, CompareOperator.LE);
            }
          // fall through
          case 72: break;
          case 26:
            { return symbol(GE, CompareOperator.GE);
            }
          // fall through
          case 73: break;
          case 27:
            { return symbol(OR);
            }
          // fall through
          case 74: break;
          case 28:
            { return symbol(LIKE, CompareOperator.LIKE);
            }
          // fall through
          case 75: break;
          case 29:
            { str_buff.append('\"');
            }
          // fall through
          case 76: break;
          case 30:
            { str_buff.append('\n');
            }
          // fall through
          case 77: break;
          case 31:
            { str_buff.append('\r');
            }
          // fall through
          case 78: break;
          case 32:
            { str_buff.append('\t');
            }
          // fall through
          case 79: break;
          case 33:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 80: break;
          case 34:
            { return symbol(NOT_LIKE, CompareOperator.NOT_LIKE);
            }
          // fall through
          case 81: break;
          case 35:
            { return symbol(AND);
            }
          // fall through
          case 82: break;
          case 36:
            { return symbol(NOT);
            }
          // fall through
          case 83: break;
          case 37:
            { return symbol(AVG, ArithmeticNodeType.AVG);
            }
          // fall through
          case 84: break;
          case 38:
            { return symbol(MAX, ArithmeticNodeType.MAX);
            }
          // fall through
          case 85: break;
          case 39:
            { return symbol(MIN, ArithmeticNodeType.MIN);
            }
          // fall through
          case 86: break;
          case 40:
            { return symbol(SUM, ArithmeticNodeType.SUM);
            }
          // fall through
          case 87: break;
          case 41:
            { return symbol(CANONICAL_COLUMN_NAME, yytext());
            }
          // fall through
          case 88: break;
          case 42:
            { return symbol(IN, CompareOperator.IN);
            }
          // fall through
          case 89: break;
          case 43:
            { return symbol(NOT_IN, CompareOperator.NOT_IN);
            }
          // fall through
          case 90: break;
          case 44:
            { return symbol(ISNULL, CompareOperator.ISNULL);
            }
          // fall through
          case 91: break;
          case 45:
            { return symbol(SUBSTRING);
            }
          // fall through
          case 92: break;
          case 46:
            { return symbol(DATE, yytext());
            }
          // fall through
          case 93: break;
          case 47:
            { return symbol(IS_NOT_NULL, CompareOperator.IS_NOT_NULL);
            }
          // fall through
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
